### ISSUE TITLE
Getting below error when trying it spark sql and scala

### ISSUE THREAD

**Issue by hsaklecha** [swoop-inc/spark-alchemy#19]
java.lang.NoClassDefFoundError: Could not initialize class com.swoop.alchemy.spark.expressions.hll.AgKn$
  at com.swoop.alchemy.spark.expressions.hll.HyperLogLogBase$.nameToImpl(HLLFunctions.scala:56)
  at com.swoop.alchemy.spark.expressions.hll.HyperLogLogBase$.$anonfun$resolveImplementation$2(HLLFunctions.scala:39)
  at scala.Option.map(Option.scala:146)
  at com.swoop.alchemy.spark.expressions.hll.HyperLogLogBase$.resolveImplementation(HLLFunctions.scala:39)
  at com.swoop.alchemy.spark.expressions.hll.HLLFunctions.hll_init_agg(HLLFunctions.scala:706)
  at com.swoop.alchemy.spark.expressions.hll.HLLFunctions.hll_init_agg$(HLLFunctions.scala:705)
  at com.swoop.alchemy.spark.expressions.hll.functions$.hll_init_agg(HLLFunctions.scala:653)
  at com.swoop.alchemy.spark.expressions.hll.HLLFunctions.hll_init_agg(HLLFunctions.scala:710)
  at com.swoop.alchemy.spark.expressions.hll.HLLFunctions.hll_init_agg$(HLLFunctions.scala:709)
  at com.swoop.alchemy.spark.expressions.hll.functions$.hll_init_agg(HLLFunctions.scala:653)
  ... 58 elided

**Comment by MrPowers** [comment]
@hsaklecha - thanks for reporting this issue.  Can you please let us know what version of Spark, Scala, and spark-alchemy you were using?  If you could reproduce the issue with a [Minimal Bug Report](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports), that'd help me debug the issue for you.  Thanks!
