### ISSUE TITLE
dependencies include a source jar, causing IHLLMetadata class not found error

### ISSUE THREAD

**Issue by krisplazonic** [swoop-inc/spark-alchemy#27]
Tried the scala example on a fresh EMR cluster, and getting this error: 

```
java.lang.NoClassDefFoundError: net/agkn/hll/serialization/IHLLMetadata
  at com.swoop.alchemy.spark.expressions.hll.HyperLogLogBase$.$anonfun$resolveImplementation$1(HLLFunctions.scala:39)
  at scala.Option.flatMap(Option.scala:271)
  at com.swoop.alchemy.spark.expressions.hll.HyperLogLogBase$.resolveImplementation(HLLFunctions.scala:39)
  at com.swoop.alchemy.spark.expressions.hll.HLLFunctions.hll_init_agg(HLLFunctions.scala:725)
  at com.swoop.alchemy.spark.expressions.hll.HLLFunctions.hll_init_agg$(HLLFunctions.scala:724)
  at com.swoop.alchemy.spark.expressions.hll.functions$.hll_init_agg(HLLFunctions.scala:672)
  ... 66 elided
Caused by: java.lang.ClassNotFoundException: net.agkn.hll.serialization.IHLLMetadata
```

Steps to reproduce: - (note the `sources` in the downloaded jars) - `hll-1.6.0-sources.jar`

```
[hadoop@ip-10-0-65-130 ~]$ spark-shell --packages com.swoop:spark-alchemy_2.12:1.2.0
:: loading settings :: url = jar:file:/usr/lib/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/hadoop/.ivy2/cache
The jars for the packages stored in: /home/hadoop/.ivy2/jars
com.swoop#spark-alchemy_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-903c632d-c058-4f0e-86bd-73a28cf3e3dd;1.0
        confs: [default]
        found com.swoop#spark-alchemy_2.12;1.2.0 in central
        found net.agkn#hll;1.6.0 in central
        found it.unimi.dsi#fastutil;6.5.11 in central
downloading https://repo1.maven.org/maven2/com/swoop/spark-alchemy_2.12/1.2.0/spark-alchemy_2.12-1.2.0.jar ...
        [SUCCESSFUL ] com.swoop#spark-alchemy_2.12;1.2.0!spark-alchemy_2.12.jar (19ms)
downloading https://repo1.maven.org/maven2/net/agkn/hll/1.6.0/hll-1.6.0-sources.jar ...
        [SUCCESSFUL ] net.agkn#hll;1.6.0!hll.jar (6ms)
downloading https://repo1.maven.org/maven2/it/unimi/dsi/fastutil/6.5.11/fastutil-6.5.11.jar ...
        [SUCCESSFUL ] it.unimi.dsi#fastutil;6.5.11!fastutil.jar (571ms)
```

**Comment by krisplazonic** [comment]
To clarify, the dependencies specified include sources jar 
```
downloading https://repo1.maven.org/maven2/net/agkn/hll/1.6.0/hll-1.6.0-sources.jar ...
```
when it should download `https://repo1.maven.org/maven2/net/agkn/hll/1.6.0/hll-1.6.0.jar`. I verified the scala and python examples from your documentation work, when I download this manually and there is no serialization error then. Somehow dependencies are declared wrong, but I don't see anything obviously wrong in maven. There are closed issues with the same error - https://github.com/swoop-inc/spark-alchemy/issues/25 and https://github.com/swoop-inc/spark-alchemy/issues/24

**Comment by pidge** [comment]
Thanks for the additional details. I was able to reproduce it and yes that's definitely weird.

Looks like I can work around it by adding the library as an explicit dependency, eg:

```
spark-shell --packages com.swoop:spark-alchemy_2.12:1.2.0,net.agkn:hll:1.6.0
```

Will dig into it more when we have the chance.

**Comment by greglu** [comment]
Thanks for the report! The [following PR](https://github.com/swoop-inc/spark-alchemy/pull/28) was created and version [1.2.1](https://github.com/swoop-inc/spark-alchemy/releases/tag/v1.2.1) has been released to Maven Central.
